PORTNAME=	francis
DISTVERSION=	${KDE_APPLICATIONS_VERSION}
CATEGORIES=	deskutils kde kde-applications

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Track your time
WWW=		https://invent.kde.org/utilities/francis

LICENSE=	LGPL3+

USES=		cmake gettext kde:6 qt:6 tar:xz
USE_KDE=	config coreaddons dbusaddons i18n kirigami-addons \
		ecm:build
USE_QT=		base declarative svg
USE_GL=		gl opengl

.include <bsd.port.mk>
